GusBusDraws/smallweb-subway.js

README.md, smallweb-subway.js
- Updated the `loadJSON()` function to take a URL as an argument
- Added change log
=> Pass json arg

README.md, smallweb-subway.js
- Rename webring data loading functions to have separate names from DoodleBot data loading
=> Rename webring data loading functions to be unique

smallweb-subway.js
Use CSS to make widget graphics
=> Add subway line graphics

smallweb-subway.js
Update references from repo name from `smallweb-subway` to `smallweb-subway.js`
=> Update repo name to smallweb-subway.js

.vscode/settings.json, README.md, creativesclub.js, creativesclub.json, doodlecrew.js, index.html
- Remove background and border style from widgets
=> Cc add end slash

README.md, poetry.js, poetry.json
- Update the README with instructions to join a line
- Add the poetry line with corresponding files!
=> Poetry line

creativesclub.json
Add https://urlocalcyb.org/ to Creatives Club JSON
=> Add UR LOCAL CYBORG

comics.js, comics.json, creativesclub.js, index.html
- Add files associated with a comics line
=> Comics line

README.md, custom/zines-bumblechub.js
- Add custom/zines-bumblechub.js as workaround for Google Sites
=> bumblechub Google Sites workaround

README.md, creativesclub.json, doodlecrew.json, index.html, poetry.js, zines.js
- Reorder Doodle Crew line to match map
- Reorder CC line to match map
- Swap colors of poetry and zines lines
=> Swap poetry zines

poetry.json, zines.json
=> Add my site please :^)

README.md, comics.json, creativesclub.json, custom/comics-yuki.js, custom/creativesclub-yuki.js
- Add yukiclarke.com to CC & Comics Lines
- Add custom/creativesclub-yuki.js
- Add custom/comics-yuki.js
=> Yuki cc comics

.vscode/settings.json, README.md, scifi.js, scifi.json
- Add files for new Scifi Line
=> Add scifi line

comics.json
PR to add the Neat Hobby! webcomic to the Smallweb Subway webring.
=> Add Neat Hobby! to comics.json

README.md, custom/scifi-yuki.js, map.js, scifi.json
- Reroute Scifi Line through Yuki's station
- Add Yuki to Comics Line
=> Yuki scifi

README.md, comics.json, map.js
- Add DiabloAfterDark to Comics Line
=> Diablo comics

README.md, creativesclub.json, doodlecrew.json, map.js
- Add granmichi to CC line
- Rearrange CC line to match map
=> Scifi doodlecrew

README.md, comics.js, index.html
- Add force new tab option to comics line
- Add force URL option to comics line
=> Comics force url

README.md, map.js
- Make the main station bigger
- Update legend to bubbles at the top (including scifi)
- Move stations declarations in [map.js](map.js) into `addStations`
- Stretch width of scifi line
- Shorten poetry line
- Make section of comics and doodlecrew lines co-linear
- Adjust top of doodlecrew line to have two levels
- Add candycaneeater07 to doodlecrew line
- Add force new tab option to comics line
- Add force URL option to comics line
=> Candycane comics

README.md, comics.json, creativesclub.js, creativesclub.json, index.html, map.js
- Add "window.top" to [creativesclub.js](creativesclub.js) test iframe exiting
- Add force URL option to creativesclub line
- Add The Fuzzy Slug to the comics line
- Make more space on comics line
=> Fuzzyslug comics

README.md, creativesclub.js, index.html, scifi.js
- Add force URL option to scifi lines
- Add force new tab option to creativesclub and scifi lines
=> Cc new tab

README.md, index.html, map.js, poetry.js, poetry.json
- Add force URL and force new tab options to poetry line
- Add "flower in binary" to poetry line
=> Flowerinbinary poetry

README.md, comics.json, map.js, poetry.json
- Add delovely and manyface to Poetry line
- Rearrange lines to better accommodate new stations
- Add Britt Coxon to Comics line
- Add Adrien Lee to Comics line
=> Comics adrien britt

README.md, comics.json, map.js, poetry.json
- Add Beyond the End and Long Gone Legends to Comics Line
=> Comics beyond legends

README.md, comics.json, map.js, poetry.json, scifi.json, zines.json
- Remove Dead Garden from Zines Line
- Add Olólùfè Collective to the Poetry Line
- Add Friction Comic to Scifi and Comics Lines
=> Friction and ololufe

README.md, comics.json, map.js, poetry.json, scifi.json, zines.json
Hi! I just found about this webring today and it looks nice, especially that subway map! I'd like to add my comic to the map if that's ok!
=> Requesting an addition to the comic line

README.md, comics.json, creativesclub.js, doodlecrew.json, scifi.js
- Fix bug in `goToNext_scifi` sending to previous
- Fix bug in `goToNext_creativesclub` sending to previous
- Update Soho's domain
=> Soho update

README.md, map.js
- Add Doug's Poetry Shack to map
- Update Soho's pages on map
- Add Doug's Poetry Shack to Poetry line
=> Map doug soho

README.md, map.js
- Add legend selection for hover/mouse
=> Legend hover

README.md, comics.js, creativesclub.js, doodlecrew.js, map.js, poetry.js, scifi.js, zines.js
- Allow widget to render even when site not yet in webring data
- Add legend selection for hover/mouse
=> Touch legend widget render

README.md, comics.js, doodlecrew.js
- Add Redux to Comics Line (still need to add to map)
- Update Hollis's site to 2025 art page
=> Hollis 2025

README.md, comics.js, map.js, poetry.js, scifi.js
- Add greycloak and teeth.dog to Poetry Line
- Add the Stardustverse to Scifi Line
- Widen Poetry line, make Comics line extend to lower left, and shrink DC line
=> Reform comics

README.md, map.js
- Restructure map logic around a single reference point (Central Station)
=> Change map ref pt

README.md, central.js, index.html
- Update colors and add station to central widget
- Position lines and station relatively in central widget
- Begin work on a condensed transfer widget ([central.js](central.js))
=> Add transfer widget

README.md, index.html, map.js, zines.js
Would it be alright to add lunaseeker.com to the Zines line? I've added the widget! Thank you very much in advance!
=> Add Lunaseeker Press to the Zines line
